### ISSUE TITLE
Cannot read property 'finished' of undefined

### ISSUE THREAD

**Issue by iamlvm** [hex7c0/transfer-rate#2]
Can this module support Http request?
As I saw in your example, the response and request are parameters of the express module.
I've tried your excellent module with the http module and I got this error.

>TypeError: Cannot read property 'finished' of undefined 
if (first[1] || (first = start), res.finished === !0) return req.transferRate = oi(req.socket, first),

I guess it came from this line: 35 of index.min.js (`var res = req.res;`). The Http request and response does not have the field '**finished**' actually.

**Comment by hex7c0** [comment]
hi sotoremydocuments, thanks for this issue
it's a deprecated code, with this refactoring ("2.0.0") should be fixed

**Comment by iamlvm** [comment]
Hi @hex7c0 , Thank for your effort.

I am curious about the accuracy of the module. I have tested the fixed module with two computer in the same LAN (One is an Ubuntu server, and another one is a client which was running in the Chrome browser). I limited the network speed in the Chrome debug network interface to **Good 2G (150ms, 450kb/s, 150kb/s)**.

I got results as the following:

> 18.54 KB/s
> 227.39 KB/s
> 1255.39 KB/s
> 2059.66 KB/s
> 2591.91 KB/s
> 2995.10 KB/s
> 3494.73 KB/s
> 4105.39 KB/s
> 4631.01 KB/s
> 5244.18 KB/s
> 5302.74 KB/s
> 6586.76 KB/s
> 6283.08 KB/s
> 7036.45 KB/s
> 7607.76 KB/s
> 2241.38 KB/s
> 8883.70 KB/s
> 9428.87 KB/s
> 12185.89 KB/s
> 9985.93 KB/s
> 10318.89 KB/s
> 13668.57 KB/s
> 12007.50 KB/s
> 11947.72 KB/s
> 12579.77 KB/s
> 18190.89 KB/s
> 6956.35 KB/s
> 4216.62 KB/s
> 15204.19 KB/s
> 20676.98 KB/s

**In the same way**, I created a server which sends a number of files to a client when it requests to the server as shown in the following:
```
      var buffer = fs.readFileSync(filename);
      var start = process.hrtime();
      res.setHeader('Content-Length', buffer.length);
      /* same result if I initiate the start value here: var start = process.hrtime(); */
      res.end(buffer);
      rate(req, res, start);
      console.log(res.transferRate);
```

The results of the test are:

> 1556.24 KB/s
> 9096.33 KB/s
> 3947.25 KB/s
> 33845.94 KB/s
> 60625.59 KB/s
> 451350.74 KB/s
> 45313.29 KB/s
> 153496.57 KB/s
> 471784.66 KB/s
> 772903.11 KB/s
> 840829.86 KB/s
> 1149756.12 KB/s
> 959976.56 KB/s
> 220469.90 KB/s
> 1133402.57 KB/s
> 1273561.96 KB/s
> 1299954.62 KB/s
> 102761.22 KB/s
> 1289920.13 KB/s
> 1343446.16 KB/s
> 1454299.55 KB/s
> 1972416.97 KB/s
> 1728681.49 KB/s
> 411029.56 KB/s
> 1667796.03 KB/s

With the same condition of the network, but the two test has a different (The second test seems to have the transfer rate greater than the first test **20 times**). To the best of my knowledge, your module calculates the transfer rate based on **socket._bytesDispatched**.

Please help me explain the difference.

**Comment by hex7c0** [comment]
mmm I've changed information about socket bytes with [net_socket_bytesread](https://nodejs.org/api/net.html#net_socket_bytesread) and [net_socket_byteswritten](https://nodejs.org/api/net.html#net_socket_byteswritten)

you should check with this [benchmark](https://github.com/hex7c0/transfer-rate/commit/ed083ac17774760c7c38000cdc84906e096b4a74)

```sh
starting "hello world" on port 3000
853.98 KB/s
```

```sh
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 400 requests
Completed 800 requests
Completed 1200 requests
Completed 1600 requests
Completed 2000 requests
Completed 2400 requests
Completed 2800 requests
Completed 3200 requests
Completed 3600 requests
Completed 4000 requests
Finished 4000 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        2 bytes

Concurrency Level:      8
Time taken for tests:   0.820 seconds
Complete requests:      4000
Failed requests:        0
Total transferred:      412000 bytes
HTML transferred:       8000 bytes
Requests per second:    4876.39 [#/sec] (mean)
Time per request:       1.641 [ms] (mean)
Time per request:       0.205 [ms] (mean, across all concurrent requests)
Transfer rate:          490.50 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       6
Processing:     0    2   1.0      1      16
Waiting:        0    1   1.0      1      16
Total:          1    2   1.1      1      16

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      2
  80%      2
  90%      2
  95%      3
  98%      5
  99%      6
 100%     16 (longest request)
```

**Comment by iamlvm** [comment]
I really appreciate what you have done to contribute this module.

However, I still doubt the accuracy of the module.
I did the same test with the same network limitation on the Chrome (**Good 2G (150ms, 450kb/s, 150kb/s**). In addition, I did an extra test to ensure that the test result by using **wondershaper**  tool in Ubuntu to limit download and upload speed of the server (**sudo wondershaper eth0 450 150**  -> Limit download: 450Kbits, and upload: 150Kbits).

I got the same results as the following (The results seem to greater than the actual rate 100 times) :

> 175266.34 KB/s
> 123098.81 KB/s
> 102282.44 KB/s
> 154081.05 KB/s
> 114552.87 KB/s
> 137036.82 KB/s
> 147101.61 KB/s
> 138269.24 KB/s
> 137181.05 KB/s
> 125617.18 KB/s
> 136681.01 KB/s

I spent the whole morning to find out the difference between the measured value and the actual network limitation. But, I am still trapped on this.

**Comment by hex7c0** [comment]
if response has the same (size), bytes are immutable.
I use https://nodejs.org/api/process.html#process_process_hrtime_time (nanoseconds) for calculate the ratio
with `new Date().getTime()` (milliseconds) values should be more stable but with less accuracy
